services:
  db:
    image: mysql:8.0
    container_name: nhatrobaobao-db
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nhatro
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env.docker
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"

  frontend:
    build:
      context: .
      dockerfile: nha-tro-fe/Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data:
